[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Cpplex"
authors = [{name = "Marc Melikyan", email = "marc.melikyan@gmail.com"}]
dynamic = ["1.0.0", "Initial release"]
